### ISSUE TITLE
Tried to continue the project, but stuck

### ISSUE THREAD

**Issue by remklov** [Sh4dows/Pirox_Server#1]
Hi,

maybe you are still active here and you can help me to continue the project. I recompiled the bot to use a different webserver, and tried to re-code the validation stuff in the bot itself. I got it working so far that he starts, but then i get the error that "pointers are not found". As far as i understand this slightly encrypted AutoIT script, it is getting the pointers out of the validation response. Do you have any idea how this works, and maybe can give me a hint?

Greets!

**Comment by Sh4dows** [comment]
Hi,
I will delete this repo, can you send me an email to sh4dows@live.fr ?

Thx :)
